/**
 * 默认快捷键配置
 */

import type { ShortcutDefinition } from '@/types/shortcuts';
import { ShortcutCategory } from '@/types/shortcuts';

/**
 * 默认快捷键列表
 */
export const defaultShortcuts: ShortcutDefinition[] = [
  // ==================== 文件操作 ====================
  {
    id: 'file.new_query',
    name: '新建查询',
    description: '创建新的SQL查询标签页',
    category: ShortcutCategory.FILE,
    key: 'n',
    modifiers: { ctrl: true },
    enabled: true,
    customizable: true,
  },
  {
    id: 'file.save',
    name: '保存',
    description: '保存当前查询',
    category: ShortcutCategory.FILE,
    key: 's',
    modifiers: { ctrl: true },
    enabled: true,
    customizable: true,
  },
  {
    id: 'file.save_as',
    name: '另存为',
    description: '将当前查询另存为新文件',
    category: ShortcutCategory.FILE,
    key: 's',
    modifiers: { ctrl: true, shift: true },
    enabled: true,
    customizable: true,
  },
  {
    id: 'file.close_tab',
    name: '关闭标签页',
    description: '关闭当前标签页',
    category: ShortcutCategory.FILE,
    key: 'w',
    modifiers: { ctrl: true },
    enabled: true,
    customizable: true,
  },
  {
    id: 'file.quit',
    name: '退出应用',
    description: '退出InfloWave应用',
    category: ShortcutCategory.FILE,
    key: 'q',
    modifiers: { ctrl: true },
    enabled: true,
    customizable: false,
  },

  // ==================== 编辑操作 ====================
  {
    id: 'edit.undo',
    name: '撤销',
    description: '撤销上一步操作',
    category: ShortcutCategory.EDIT,
    key: 'z',
    modifiers: { ctrl: true },
    enabled: true,
    customizable: false,
  },
  {
    id: 'edit.redo',
    name: '重做',
    description: '重做上一步操作',
    category: ShortcutCategory.EDIT,
    key: 'y',
    modifiers: { ctrl: true },
    enabled: true,
    customizable: false,
  },
  {
    id: 'edit.cut',
    name: '剪切',
    description: '剪切选中内容',
    category: ShortcutCategory.EDIT,
    key: 'x',
    modifiers: { ctrl: true },
    enabled: true,
    customizable: false,
  },
  {
    id: 'edit.copy',
    name: '复制',
    description: '复制选中内容',
    category: ShortcutCategory.EDIT,
    key: 'c',
    modifiers: { ctrl: true },
    enabled: true,
    customizable: false,
  },
  {
    id: 'edit.paste',
    name: '粘贴',
    description: '粘贴剪贴板内容',
    category: ShortcutCategory.EDIT,
    key: 'v',
    modifiers: { ctrl: true },
    enabled: true,
    customizable: false,
  },
  {
    id: 'edit.select_all',
    name: '全选',
    description: '选择全部内容',
    category: ShortcutCategory.EDIT,
    key: 'a',
    modifiers: { ctrl: true },
    enabled: true,
    customizable: false,
  },
  {
    id: 'edit.find',
    name: '查找',
    description: '在当前文档中查找',
    category: ShortcutCategory.EDIT,
    key: 'f',
    modifiers: { ctrl: true },
    enabled: true,
    customizable: true,
  },
  {
    id: 'edit.replace',
    name: '替换',
    description: '查找并替换',
    category: ShortcutCategory.EDIT,
    key: 'h',
    modifiers: { ctrl: true },
    enabled: true,
    customizable: true,
  },

  // ==================== 视图导航 ====================
  {
    id: 'nav.dashboard',
    name: '仪表板',
    description: '打开仪表板页面',
    category: ShortcutCategory.NAVIGATION,
    key: '1',
    modifiers: { ctrl: true },
    enabled: true,
    customizable: true,
  },
  {
    id: 'nav.connections',
    name: '连接管理',
    description: '打开连接管理页面',
    category: ShortcutCategory.NAVIGATION,
    key: '2',
    modifiers: { ctrl: true },
    enabled: true,
    customizable: true,
  },
  {
    id: 'nav.query',
    name: '数据查询',
    description: '打开数据查询页面',
    category: ShortcutCategory.NAVIGATION,
    key: '3',
    modifiers: { ctrl: true },
    enabled: true,
    customizable: true,
  },
  {
    id: 'nav.database',
    name: '数据库管理',
    description: '打开数据库管理页面',
    category: ShortcutCategory.NAVIGATION,
    key: '4',
    modifiers: { ctrl: true },
    enabled: true,
    customizable: true,
  },
  {
    id: 'nav.visualization',
    name: '数据可视化',
    description: '打开数据可视化页面',
    category: ShortcutCategory.NAVIGATION,
    key: '5',
    modifiers: { ctrl: true },
    enabled: true,
    customizable: true,
  },
  {
    id: 'nav.performance',
    name: '性能监控',
    description: '打开性能监控页面',
    category: ShortcutCategory.NAVIGATION,
    key: '6',
    modifiers: { ctrl: true },
    enabled: true,
    customizable: true,
  },

  // ==================== 视图控制 ====================
  {
    id: 'view.toggle_sidebar',
    name: '切换侧边栏',
    description: '显示/隐藏侧边栏',
    category: ShortcutCategory.VIEW,
    key: 'b',
    modifiers: { ctrl: true },
    enabled: true,
    customizable: true,
  },
  {
    id: 'view.zoom_in',
    name: '放大',
    description: '放大界面',
    category: ShortcutCategory.VIEW,
    key: '=',
    modifiers: { ctrl: true },
    enabled: true,
    customizable: true,
  },
  {
    id: 'view.zoom_out',
    name: '缩小',
    description: '缩小界面',
    category: ShortcutCategory.VIEW,
    key: '-',
    modifiers: { ctrl: true },
    enabled: true,
    customizable: true,
  },
  {
    id: 'view.zoom_reset',
    name: '重置缩放',
    description: '重置界面缩放',
    category: ShortcutCategory.VIEW,
    key: '0',
    modifiers: { ctrl: true },
    enabled: true,
    customizable: true,
  },

  // ==================== 数据库操作 ====================
  {
    id: 'db.new_connection',
    name: '新建连接',
    description: '创建新的数据库连接',
    category: ShortcutCategory.DATABASE,
    key: 'n',
    modifiers: { ctrl: true, shift: true },
    enabled: true,
    customizable: true,
  },
  {
    id: 'db.test_connection',
    name: '测试连接',
    description: '测试当前数据库连接',
    category: ShortcutCategory.DATABASE,
    key: 't',
    modifiers: { ctrl: true },
    enabled: true,
    customizable: true,
  },
  {
    id: 'db.refresh',
    name: '刷新结构',
    description: '刷新数据库结构树',
    category: ShortcutCategory.DATABASE,
    key: 'F5',
    modifiers: {},
    enabled: true,
    customizable: true,
  },
  {
    id: 'db.delete',
    name: '删除',
    description: '删除选中项',
    category: ShortcutCategory.DATABASE,
    key: 'Delete',
    modifiers: {},
    enabled: true,
    customizable: true,
  },
  {
    id: 'db.rename',
    name: '重命名',
    description: '重命名选中项',
    category: ShortcutCategory.DATABASE,
    key: 'F2',
    modifiers: {},
    enabled: true,
    customizable: true,
  },

  // ==================== 查询操作 ====================
  {
    id: 'query.execute',
    name: '执行查询',
    description: '执行当前SQL查询',
    category: ShortcutCategory.QUERY,
    key: 'Enter',
    modifiers: { ctrl: true },
    enabled: true,
    customizable: true,
  },
  {
    id: 'query.stop',
    name: '停止查询',
    description: '停止正在执行的查询',
    category: ShortcutCategory.QUERY,
    key: 'c',
    modifiers: { ctrl: true, shift: true },
    enabled: true,
    customizable: true,
  },
  {
    id: 'query.format',
    name: '格式化查询',
    description: '格式化SQL查询语句',
    category: ShortcutCategory.QUERY,
    key: 'l',
    modifiers: { ctrl: true },
    enabled: true,
    customizable: true,
  },
  {
    id: 'query.comment',
    name: '注释/取消注释',
    description: '注释或取消注释选中行',
    category: ShortcutCategory.QUERY,
    key: '/',
    modifiers: { ctrl: true },
    enabled: true,
    customizable: true,
  },
  {
    id: 'query.history',
    name: '查询历史',
    description: '打开查询历史记录',
    category: ShortcutCategory.QUERY,
    key: 'h',
    modifiers: { ctrl: true, shift: true },
    enabled: true,
    customizable: true,
  },

  // ==================== 搜索 ====================
  {
    id: 'search.global',
    name: '全局搜索',
    description: '打开全局搜索',
    category: ShortcutCategory.SEARCH,
    key: 'p',
    modifiers: { ctrl: true, shift: true },
    enabled: true,
    customizable: true,
  },

  // ==================== 工具 ====================
  {
    id: 'tools.settings',
    name: '应用设置',
    description: '打开应用设置',
    category: ShortcutCategory.TOOLS,
    key: ',',
    modifiers: { ctrl: true },
    enabled: true,
    customizable: true,
  },
  {
    id: 'tools.shortcuts',
    name: '快捷键帮助',
    description: '显示快捷键列表',
    category: ShortcutCategory.TOOLS,
    key: 'k',
    modifiers: { ctrl: true },
    enabled: true,
    customizable: true,
  },
  {
    id: 'tools.user_manual',
    name: '用户手册',
    description: '打开用户手册',
    category: ShortcutCategory.TOOLS,
    key: 'F1',
    modifiers: {},
    enabled: true,
    customizable: true,
  },

  // ==================== 窗口管理 ====================
  {
    id: 'window.minimize',
    name: '最小化',
    description: '最小化窗口',
    category: ShortcutCategory.WINDOW,
    key: 'm',
    modifiers: { ctrl: true },
    enabled: true,
    customizable: false,
  },
  {
    id: 'window.fullscreen',
    name: '全屏',
    description: '切换全屏模式',
    category: ShortcutCategory.WINDOW,
    key: 'F11',
    modifiers: {},
    enabled: true,
    customizable: false,
  },
  {
    id: 'window.devtools',
    name: '开发者工具',
    description: '打开开发者工具',
    category: ShortcutCategory.WINDOW,
    key: 'F12',
    modifiers: {},
    enabled: true,
    customizable: false,
  },

  // ==================== 通用 ====================
  {
    id: 'general.refresh',
    name: '刷新页面',
    description: '刷新当前页面',
    category: ShortcutCategory.GENERAL,
    key: 'F5',
    modifiers: {},
    enabled: true,
    customizable: false,
  },
  {
    id: 'general.escape',
    name: '取消/关闭',
    description: '取消当前操作或关闭对话框',
    category: ShortcutCategory.GENERAL,
    key: 'Escape',
    modifiers: {},
    enabled: true,
    customizable: false,
  },
];

/**
 * 快捷键类别信息
 */
export const shortcutCategoryInfo = {
  [ShortcutCategory.FILE]: {
    label: '文件操作',
    description: '文件相关的操作',
  },
  [ShortcutCategory.EDIT]: {
    label: '编辑操作',
    description: '文本编辑相关的操作',
  },
  [ShortcutCategory.VIEW]: {
    label: '视图控制',
    description: '界面视图相关的操作',
  },
  [ShortcutCategory.DATABASE]: {
    label: '数据库操作',
    description: '数据库管理相关的操作',
  },
  [ShortcutCategory.QUERY]: {
    label: '查询操作',
    description: 'SQL查询相关的操作',
  },
  [ShortcutCategory.TOOLS]: {
    label: '工具功能',
    description: '工具和设置相关的操作',
  },
  [ShortcutCategory.WINDOW]: {
    label: '窗口管理',
    description: '窗口控制相关的操作',
  },
  [ShortcutCategory.NAVIGATION]: {
    label: '页面导航',
    description: '页面切换相关的操作',
  },
  [ShortcutCategory.SEARCH]: {
    label: '搜索功能',
    description: '搜索相关的操作',
  },
  [ShortcutCategory.DEVELOPER]: {
    label: '开发者工具',
    description: '开发调试相关的操作',
  },
  [ShortcutCategory.GENERAL]: {
    label: '通用操作',
    description: '通用的系统操作',
  },
};

