name: ç®€åŒ–ç‰ˆå‘å¸ƒæž„å»º

# è¿™æ˜¯ä¸€ä¸ªç®€åŒ–ç‰ˆçš„ workflowï¼Œé€‚ç”¨äºŽ Gitee Go åŠŸèƒ½å—é™çš„æƒ…å†µ
# åªæž„å»ºä¸»è¦å¹³å°çš„ä¸»è¦æž¶æž„

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'ç‰ˆæœ¬å·ï¼ˆå¦‚ 1.0.0ï¼‰'
        required: true
        type: string

permissions:
  contents: write

jobs:
  # Windows x64 æž„å»º
  build-windows-x64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: è®¾ç½® Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc
          override: true

      - name: è®¾ç½® Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: å®‰è£…ä¾èµ–
        run: npm ci

      - name: æž„å»º
        run: npm run tauri build

      - name: ä¸Šä¼ äº§ç‰©
        uses: actions/upload-artifact@v3
        with:
          name: windows-x64
          path: |
            src-tauri/target/release/bundle/**/*.msi
            src-tauri/target/release/bundle/**/*.exe

  # Linux x64 æž„å»º
  build-linux-x64:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: å®‰è£…ç³»ç»Ÿä¾èµ–
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.0-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            patchelf

      - name: è®¾ç½® Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: è®¾ç½® Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: å®‰è£…ä¾èµ–
        run: npm ci

      - name: æž„å»º
        run: npm run tauri build

      - name: ä¸Šä¼ äº§ç‰©
        uses: actions/upload-artifact@v3
        with:
          name: linux-x64
          path: |
            src-tauri/target/release/bundle/**/*.deb
            src-tauri/target/release/bundle/**/*.AppImage

  # macOS æž„å»ºï¼ˆä»… x64ï¼‰
  build-macos-x64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: è®¾ç½® Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          override: true

      - name: è®¾ç½® Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: å®‰è£…ä¾èµ–
        run: npm ci

      - name: æž„å»º
        run: npm run tauri build -- --target x86_64-apple-darwin

      - name: ä¸Šä¼ äº§ç‰©
        uses: actions/upload-artifact@v3
        with:
          name: macos-x64
          path: |
            src-tauri/target/x86_64-apple-darwin/release/bundle/**/*.dmg

  # åˆ›å»ºå‘å¸ƒ
  create-release:
    needs: [build-windows-x64, build-linux-x64, build-macos-x64]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: èŽ·å–ç‰ˆæœ¬å·
        id: get_version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION="${GITHUB_REF#refs/tags/v}"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: ä¸‹è½½æ‰€æœ‰äº§ç‰©
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: å‡†å¤‡å‘å¸ƒæ–‡ä»¶
        run: |
          mkdir -p release-files
          find artifacts -type f \( -name "*.msi" -o -name "*.exe" -o -name "*.deb" -o -name "*.AppImage" -o -name "*.dmg" \) -exec cp {} release-files/ \;
          ls -lh release-files/

      - name: ç”Ÿæˆå‘å¸ƒè¯´æ˜Ž
        id: release_notes
        run: |
          cat > release_notes.md << 'EOF'
          ## InfloWave v${{ steps.get_version.outputs.version }}
          
          ### ðŸ“¦ ä¸‹è½½
          
          #### Windows
          - MSI å®‰è£…åŒ…ï¼ˆæŽ¨èï¼‰
          - EXE å®‰è£…åŒ…
          
          #### Linux
          - DEB åŒ…ï¼ˆDebian/Ubuntuï¼‰
          - AppImageï¼ˆé€šç”¨ï¼‰
          
          #### macOS
          - DMG å®‰è£…åŒ…ï¼ˆIntel Macï¼‰
          
          ### ðŸ“ æ›´æ–°å†…å®¹
          
          è¯·æŸ¥çœ‹å®Œæ•´çš„ [æ›´æ–°æ—¥å¿—](CHANGELOG.md)
          
          ### ðŸ”§ å®‰è£…è¯´æ˜Ž
          
          è¯¦è§ [ç”¨æˆ·æ–‡æ¡£](user-docs/)
          EOF
          
          cat release_notes.md

      - name: åˆ›å»º Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: InfloWave v${{ steps.get_version.outputs.version }}
          body_path: release_notes.md
          files: release-files/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITEE_TOKEN }}

